stages:
  extract_dataset:
    cmd: python ./src/data/extract_dataset.py
    deps:
      - ./src/data/extract_dataset.py
      - ./data/raw/zipped_file/complaints.zip
    outs:
      - ./data/extracted_data/complaints.csv

  data_preprocessing:
    cmd: python ./src/features/data_preprocessing.py complaints.csv
    deps:
      - ./src/features/data_preprocessing.py
      - ./data/extracted_data/complaints.csv
    outs:
      - ./data/processed/preprocessed.csv

  

  