stages:
  extract_dataset:
    cmd: python ./src/data/extract_dataset.py
    deps:
      - ./src/data/extract_dataset.py
      - ./data/raw/zipped_file/complaints.zip
    outs:
      - ./data/extracted_data/complaints.csv

  data_preprocessing:
    cmd: python ./src/features/data_preprocessing.py complaints.csv
    deps:
      - ./src/features/data_preprocessing.py
      - ./data/extracted_data/complaints.csv
    outs:
      - ./data/processed/preprocessed.csv

  make_dataset:
    cmd: python ./src/data/make_dataset.py preprocessed.csv
    deps:
      - ./data/processed/preprocessed.csv
      - ./src/data/make_dataset.py
    params:
      - make_dataset.test_size
      - make_dataset.random_state
    outs:
      - ./data/interim/train.csv
      - ./data/interim/test.csv

  feature_engineering:
    cmd: python ./src/features/feature_engineering.py
    deps:
      - ./src/features/feature_engineering.py
      - ./data/interim/train.csv
      - ./data/interim/test.csv
    outs:
      - ./data/feature/train_features.npz
      - ./data/feature/train_target.joblib
      - ./data/feature/test_features.npz
      - ./data/feature/test_target.joblib

  train_model:
    cmd: python ./src/models/train_model.py data/feature/train_features.npz data/feature/train_target.joblib
    deps:
      - ./src/models/train_model.py
      - ./data/feature/train_features.npz
      - ./data/feature/train_target.joblib
    outs:
      - ./models/model.joblib
